const ADD_CLUB = 'ADD_CLUB';
const RESET_CLUB = 'RESET_CLUB';
const REMOVE_CLUB = 'REMOVE_CLUB';
const FETCH_CLUBS = 'FETCH_CLUBS'

export default {
    ADD_CLUB,
    RESET_CLUB,
    REMOVE_CLUB,
    FETCH_CLUBS
}